apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30s
  path: ./flux/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
