apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  path: ./flux/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
  wait: true
