apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  releaseName: traefik
  targetNamespace: kube-system
  chart:
    spec:
      chart: traefik
      version: "21.1.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 24h
